name: HoloItems
version: 1.11
author: klin
main: com.klin.holoItems.HoloItems
api-version: 1.14
commands:
  collections:
    usage: /<command>
  acquire:
    usage: /<command> <id>
  registry:
    usage: /<command>
  disable:
    usage: /<command> <id>
  enable:
    usage: /<command> <id>
  collect:
    usage: /<command> <stat> <type> <id>
  gethead:
    usage: /<command> <name>