name: HoloItems
version: 1.17
author: klin
main: com.klin.holoItems.HoloItems
api-version: 1.14

commands:
  collections:
    permission: holoItems.player
    usage: /<command>
  coordinates:
    permission: holoItems.player
    usage: /<command>
  custommodeldata:
    permission: holoItems.player
    usage: /<command>
  registry:
    permission: holoItems.player
    usage: /<command>
  worldname:
    permission: holoItems.player
    usage: /<command>
  acquire:
    permission: holoItems.player
    usage: /<command> <id>

  accelerate:
    permission: holoItems.op
    usage: /<command> <x> <y> <z>
  canceltasks:
    permission: holoItems.op
    usage: /<command>
  clearactivatables:
    permission: holoItems.op
    usage: /<command>
  collect:
    permission: holoItems.op
    usage:
      /<command> <stat> <type> <id>
  disable:
    permission: holoItems.op
    usage: /<command> <id>
  enable:
    permission: holoItems.op
    usage: /<command> <id>
  getactivatables:
    permission: holoItems.op
    usage: /<command>
  gethead:
    permission: holoItems.op
    usage: /<command> <name>
  getmap:
    permission: holoItems.op
    usage: /<command> <index>
  removechunktickets:
    permission: holoItems.op
    usage: /<command>
  setcustommodeldata:
    permission: holoItems.op
    usage: /<command> <custommodeldata>
  setenchantments:
    permission: holoItems.op
    usage: /<command> <enchantments>
  settype:
    permission: holoItems.op
    usage: /<command> <type>
  test:
    permission: holoItems.op
    usage: /<command>
  
  inadungeon:
    permission: holoItems.dungeon
    usage: /<command>

  build:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <name> <world> <x> <y> <z>
  tostring:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x1> <y1> <z1> <x2> <y2> <z2> <name>
  groundpound:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <entityType>
  paintbomb:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>
  spreadfire:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>
  freeze:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command>
  select:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>
  resetselect:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command>
  conduit:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>
  resetconduit:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command>
  plant:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>
  resetgettingwood:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command>
  minesweeper:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x1> <x2> <z1> <z2> <y>
  resetminesweeper:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command>
  class:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <class>
  maintain:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <x1> <z1> <x2> <z2>
  resetmaintenance:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command>
  payload:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <xStart> <yStart> <zStart> <x1> <y1> <z1> <x2> <y2> <z2> <direction>
  spawn:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <index> <world> <x> <y> <z>
  waterfall:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command> <world> <x> <y> <z>
  resetwaterfall:
    permission: holoItems.dungeons.inaDungeon
    usage: /<command>

permissions:
  holoItems.*:
    default: op
    children:
      holoItems.player: true
      holoItems.op: true
      holoItems.dungeons: true
  holoItems.player:
    default: true
  holoItems.op:
    default: false
  holoitems.dungeons:
    default: false
