name: HoloItems
version: 1.17
author: klin
main: com.klin.holoItems.HoloItems
api-version: 1.14
commands:
  collections:
    usage: /<command>
  worldname:
    usage: /<command>
  custommodeldata:
    usage: /<command>
  acquire:
    usage: /<command> <id>
  registry:
    usage: /<command>
  disable:
    usage: /<command> <id>
  enable:
    usage: /<command> <id>
  collect:
    usage: /<command> <stat> <type> <id>
  gethead:
    usage: /<command> <name>
  setcustommodeldata:
    usage: /<command> <custommodeldata>
  settype:
    usage: /<command> <type>
  setenchantments:
    usage: /<command> <enchantments>
  removechunktickets:
    usage: /<command>
  getactivatables:
    usage: /<command>
  clearactivatables:
    usage: /<command>
  test:
    usage: /<command>
  tostring:
    usage: /<command> <x1> <y1> <z1> <x2> <y2> <z2>
  build:
    usage: /<command> <index>
  spreadfire:
    usage: /<command> <x> <y> <z>
  paintbomb:
    usage: /<command> <x> <y> <z>
  groundpound:
    usage: /<command> <entityType>
  minesweeper:
    usage: /<command> <x1> <x2> <z1> <z2> <y> <world>
  reset:
    usage: /<command>
  spawn:
    usage: /<command> <index> <world> <x> <y> <z>
  payload:
    usage: /<command> <world> <xStart> <yStart> <zStart> <x1> <y1> <z1> <x2> <y2> <z2> <direction>